### ISSUE TITLE
Could it be viable?

### ISSUE THREAD

**Issue by sandervanhooft** [ItsDizzy/laravel-cashier-mollie#2]
Hi @ItsDizzy,

I've researched the integration of Laravel Cashier and Mollie in before.

At that time [I came to the conclusion](https://www.sandervanhooft.nl/blog/laravel/when-laravel-cashier-will-not-help-you) that it was not viable as Cashier works with payment tokens (Stripe / Braintree) instead of redirecting the customer to a payment page like Mollie. Cashier was too closely tied to the Stripe and Braintree APIs.

Have you found a workaround for this issue? Because that would be great!

(I also got a no-go response from Taylor Otwell by the way when I had the same question for integrating Laravel Spark with Mollie.)

Kind regards,

Sander

**Comment by paulhobbel** [comment]
You are correct, mollie works completely different unfortunally. However imma try to implement cashier in a different way. If you'd like to help I would be really thankful

**Comment by paulhobbel** [comment]
I was thinking about only changing the payment part. Ofcourse there are some features in cashier whose aren't supported in Mollie, it might be a good idea to either remove those or give cashier-mollie it's own logic for those.

**Comment by sandervanhooft** [comment]
Hi @ItsDizzy,

Because of the discrepancies with Cashier I decided to focus on the functional requirements instead and roll my own solutions. I think the differences are just too large to overcome. (Feel free to prove me wrong :)).

I currently have two packages to help implementing Mollie payments in Laravel:

1. [a package for Mollie payments](http://github.com/sandervanhooft/laravel-payable-redirect-mollie). It currently only supports one-off payments.

2. [a package for invoice (and pdf) generation](http://github.com/sandervanhooft/laravel-invoicable). It is heavily inspired by Cashier - but payment gateway agnostic.

I hope this helps you.

Sander

**Comment by sandervanhooft** [comment]
Mollie has asked me to look into this. https://github.com/mollie/laravel-mollie/issues/20#issuecomment-402199131
